### ISSUE TITLE
[META] Use B2B 

### ISSUE THREAD

**Issue by jrbeeman** [balsama/engage-demo#10]
🖼= Needs asset from ASH.

**Menus and other blocks**
- [x] 🖼Umami logo: Swap with generic B2B logo.
- [x] Head nav: Swap “Articles” for “Press releases” 
- [x] Search box default text: Change to “Search by keyword” 
- [x] 🖼Footer block: Swap image and “Umami food magazine” to something about getting in touch with us.
- [x] Very bottom footer: Change “Umami Magazine & Umami Publications is a fictional magazine and publisher for illustrative purposes only.” to "bread&butter is a fictional B2B company, for illustrative purposes only."

**Content**
- [x] 🖼Homepage hero block (Umami Recipes Banner): Change title, image, and copy.
- [x] All article titles: Change to something business-y
- [ ] Default user name: Change from “Umami” to a "bread&butter"
- [x] Recipes: Change to "Press release." Hide cooking time / difficulty fields.
- [x] 🖼Articles: Create three business-y articles w/ business-y images so that article page lists appropriate content and these new articles can be used in landing page.
- [x] Content scheduling: Use a new article
- [x] Landing page: Use updated homepage hero block, use new articles

**Comment by balsama** [comment]
This is built out to [stage](http://engagedemokksecgvwvg.devcloud.acquia-sites.com/). Let's use that environment to start checking off boxes.

**Comment by balsama** [comment]
@jrbeeman have you coordinated with ASH re assets?

**Comment by jrbeeman** [comment]
@balsama sure have! She said she'll have assets put together in a Google Drive folder sometime today.

>Decided to go with a spin on a service like Square, the payment service used by small businesses. Something along the lines of:
>_Because balancing your books shouldn’t be what’s keeping you up at night_
>Molly came up with
>_Balancing the books is our bread&butter_
>and so we’re calling the company bread&butter

**Comment by balsama** [comment]
See PR #13. This will likely need another round of review feedback.

**Comment by balsama** [comment]
> Default user name: Change from “Umami” to a "bread&butter"

I haven't changed that username but I don't think it's used anywhere?
